In this session, we are going to see the post-process result of covid delta mutation escape mutant priority rank.

In [11]:
import pandas as pd
file_name = "extended_analyze_semantics_delta_bilstm_512.csv"
delta_df = pd.read_csv(file_name, sep='\t')
delta_df

       pos wt mut          prob     change  is_viable  is_escape   codon indep
0        2  F   A  7.775681e-05  2150.6333       True      False  3.527765e-10
1        2  F   C  2.815297e-05  2666.2922       True      False  6.883835e-06
2        2  F   D  5.020854e-07  2009.4619       True      False  5.212324e-11
3        2  F   E  1.228403e-05  2327.1394       True      False  7.534191e-16
4        3  V   A  1.159353e-06  1534.3430       True      False  5.124971e-05
...    ... ..  ..           ...        ...        ...        ...           ...
24125    2  F   S  7.167592e-05  1777.6849       True      False  5.124976e-05
24126    2  F   T  1.079369e-05  1696.6838       True      False  3.880541e-10
24127    2  F   V  1.586966e-03  1831.0867       True      False  6.883935e-06
24128    2  F   W  4.212665e-07  1683.0480       True      False  4.738233e-11
24129    2  F   Y  1.663047e-04  1572.5698       True      False  7.572219e-06

[24130 rows x 8 columns]

In [12]:
# Mark is_escape label manually
escape_df = delta_df[delta_df['is_escape'] == True]
escape_df

       pos wt mut      prob     change  is_viable  is_escape   codon indep
4524   453  L   F  0.006322  6650.6377       True       True  2.176122e-05
20130  444  G   S  0.100879  3036.1982       True       True  1.474261e-08
20132  444  G   V  0.004342  3887.5127       True       True  8.264059e-10

In [13]:
"""Make rank of 'prob', 'change', 'codon indep'.
"""
rank_names = ['grammar rank', 'sem change rank', 'indep rank']
score_names = ['prob', 'change', 'codon indep']
def rank_helper(df, rank_names, score_names):
    df[rank_names] = df[score_names].rank(method="min", ascending=False)

rank_helper(delta_df, rank_names, score_names)
delta_df

,pos,wt,mut,prob,change,is_viable,is_escape,codon indep,grammar rank,sem change rank,indep rank
0,2,F,A,7.775681e-05,2150.6333,True,False,3.527765e-10,3503.0,20768.0,17400.0
1,2,F,C,2.815297e-05,2666.2922,True,False,6.883835e-06,5178.0,17592.0,8020.0
2,2,F,D,5.020854e-07,2009.4619,True,False,5.212324e-11,14020.0,21459.0,19711.0
3,2,F,E,1.228403e-05,2327.1394,True,False,7.534191e-16,6857.0,19795.0,24057.0
4,3,V,A,1.159353e-06,1534.3430,True,False,5.124971e-05,12222.0,23064.0,3168.0
...,...,...,...,...,...,...,...,...,...,...,...
24125,2,F,S,7.167592e-05,1777.6849,True,False,5.124976e-05,3621.0,22352.0,3113.0
24126,2,F,T,1.079369e-05,1696.6838,True,False,3.880541e-10,7139.0,22603.0,16915.0
24127,2,F,V,1.586966e-03,1831.0867,True,False,6.883935e-06,677.0,22146.0,7857.0
24128,2,F,W,4.212665e-07,1683.0480,True,False,4.738233e-11,14394.0,22648.0,19968.0
24129,2,F,Y,1.663047e-04,1572.5698,True,False,7.572219e-06,2431.0,22966.0,7223.0

In [14]:
from itertools import combinations
"""make combined rank"""
def combined_rank_helper(df, rank_names, num):
    for combined_rank in combinations(rank_names, num):
        df['+'.join(combined_rank) + " rank"] = (df[list(combined_rank)].sum(axis=1)).rank(method='min')
combined_rank_helper(delta_df, rank_names, 1)
combined_rank_helper(delta_df, rank_names, 2)
combined_rank_helper(delta_df, rank_names, 3)
delta_df

,pos,wt,mut,prob,change,is_viable,is_escape,codon indep,grammar rank,sem change rank,indep rank,grammar rank rank,sem change rank rank,indep rank rank,grammar rank+sem change rank rank,grammar rank+indep rank rank,sem change rank+indep rank rank,grammar rank+sem change rank+indep rank rank
0,2,F,A,7.775681e-05,2150.6333,True,False,3.527765e-10,3503.0,20768.0,17400.0,3503.0,20768.0,17400.0,12293.0,9540.0,22087.0,16282.0
1,2,F,C,2.815297e-05,2666.2922,True,False,6.883835e-06,5178.0,17592.0,8020.0,5178.0,17592.0,8020.0,10571.0,4153.0,13659.0,8175.0
2,2,F,D,5.020854e-07,2009.4619,True,False,5.212324e-11,14020.0,21459.0,19711.0,14020.0,21459.0,19711.0,21313.0,19209.0,23120.0,22651.0
3,2,F,E,1.228403e-05,2327.1394,True,False,7.534191e-16,6857.0,19795.0,24057.0,6857.0,19795.0,24057.0,14857.0,17451.0,23727.0,21275.0
4,3,V,A,1.159353e-06,1534.3430,True,False,5.124971e-05,12222.0,23064.0,3168.0,12222.0,23064.0,3168.0,21232.0,5498.0,14244.0,14007.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24125,2,F,S,7.167592e-05,1777.6849,True,False,5.124976e-05,3621.0,22352.0,3113.0,3621.0,22352.0,3113.0,14188.0,1233.0,13503.0,6922.0
24126,2,F,T,1.079369e-05,1696.6838,True,False,3.880541e-10,7139.0,22603.0,16915.0,7139.0,22603.0,16915.0,17647.0,12192.0,22568.0,19405.0
24127,2,F,V,1.586966e-03,1831.0867,True,False,6.883935e-06,677.0,22146.0,7857.0,677.0,22146.0,7857.0,10631.0,1885.0,17426.0,8094.0
24128,2,F,W,4.212665e-07,1683.0480,True,False,4.738233e-11,14394.0,22648.0,19968.0,14394.0,22648.0,19968.0,22048.0,19564.0,23511.0,23015.0
24129,2,F,Y,1.663047e-04,1572.5698,True,False,7.572219e-06,2431.0,22966.0,7223.0,2431.0,22966.0,7223.0,13612.0,2331.0,17560.0,9561.0

In [ ]:
def mean_std_helper(df, name):
    return f'mean and std of {name} is\t{df[name].mean()},\t{df[name].std()}'

delta_escape_df = delta_df[delta_df['is_escape'] == True]

with open('delta_escape_result.txt', 'w') as file:
    for text in map(lambda x: mean_std_helper(delta_escape_df, x), filter(lambda string: "rank rank" in string, delta_escape_df.columns)):
        print(text)
        file.write(text + '\n')